### ISSUE TITLE
Spring boot starter reactive does not loading secondary indexes into cache on startup

### ISSUE THREAD

**Issue by tdanylchuk** [aerospike-community/spring-boot-data-aerospike#19]
https://github.com/aerospike-community/spring-boot-data-aerospike/blob/master/spring-boot-autoconfigure-data-aerospike/src/main/java/org/springframework/boot/autoconfigure/data/aerospike/AerospikeReactiveDataConfiguration.java#L74

creating bean but not loading existing indexes from aerospike server, hence all queries which based on secondary index failing on disabled scan guard.

Tips to consider: we need somehow to use same confgiuration classes as spring-data project and somehow omit ConditionOn issue, so we keep 1 place for misstake and not copy-paste code each time we add new bean to **spring-data** configurations

**Comment by Aloren** [comment]
fixed via #21
@tdanylchuk let's discuss ways of improvement current approach separately
