### ISSUE TITLE
Repo.spring.io access

### ISSUE THREAD

**Issue by joincamp** [aerospike-community/spring-boot-data-aerospike#29]
This repository seems to rely on a past history of your artifacts being allowed into repo.spring.io, but [this no longer appears to be the case](https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020). Is there a way that you can still share this with the end-user-dev without them having to personally set up and publish all the `com.aerospike` dependencies?

**Comment by Aloren** [comment]
Hi @joincamp. Unfortunately releases are not currently available to the public in maven central. But you may still fork it for now and release internally. Sorry for the inconveniences.
